server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql:///es
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  type-aliases-package: cn.itcast.hotel.pojo

